### PR TITLE
kinetic-scroll-view: use mx_adjustment_interpolate instead  of mx_adjustment_set_value

### PR DESCRIPTION
**Pull request by rodrmoya**
...ent_set_value

This prevents "jumps" when getting events from low resolution input devices,
so that the panning movement is continous.

### CODE REVIEW

**Comment by djdeath** [comment]
Not that I don't want to see you problem fixed, but it sounds like this is just a workaround for a particular hardware case. You might encounter this problem with other widgets/actions/etc.. like a ClutterDragAction/RotateAction/ZoomAction...
So to me it makes more sense to work around that problem either at the driver level or backend level by adding events to fill the gaps.

**Comment by tomeuv** [comment]
This problem is most visible with crappy hardware and/or input drivers, but is not restricted to it. If the user's finger moves fast enough, user experience will be crappy without interpolation. Is there any major platform out there that doesn't interpolate scrolling positions when panning with touch?

**Comment by djdeath** [comment]
Well pretty much everything in Clutter/GTK+ doesn't interpolate on motion events.

**Comment by tomeuv** [comment]
Well, by major platform that uses touch extensively, guess I meant iOS and Android :)

**Pull request closed without merging**
