### PR TITLE
Introducing slide-start/stop signals on the MxSlider

### PR DESCRIPTION
**Pull request by ghost**
Reworked a patch from Massimo Corà mcora@src.gnome.org

### CODE REVIEW

**Comment by Cwiiis** [comment]
Going with Thomas's original comment, we probably don't need the class handlers, but I don't have any strong feelings either way. Looks good to me. I'll leave merging to the people that still actively work on this, of course :)

**Comment by ghost** [comment]
Removed signal handlers + another patch unrelated.

**Comment by thos** [comment]
Please push the relevant patch to master.

**Comment by ghost** [comment]
Done.

**Pull request closed without merging**
