### PR TITLE
No actor for background image

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by thos** [comment]
Commits 9aed87c and fa7a9e2 look fine.

Commit c3abeb2 adds a new function to mx-texture-frame.c, but has nothing to do with the purpose of texture frame. Shouldn't this function just be in mx-widget.c?

**Comment by thos** [comment]
It might also be worth making the default drawing behaviour match that of CSS's background-image property, i.e. repeat the image starting from the top left.

**Comment by thos** [comment]
Are these last two commits related to the background-image?

**Comment by ghost** [comment]
Nop, that is something different.
This third one though fixes the arrow problem on tooltips.

**Comment by thos** [comment]
I've pushed the four relevant commits to master and added another commit to move the painting utility function to the private API.

**Pull request closed without merging**
