### PR TITLE
mx-kinetic-scroll-view: respect scroll policy

### PR DESCRIPTION
**Pull request by ManMower**
Previously the scroll policy was only obeyed until the contents began to drag

### CODE REVIEW

**Comment by djdeath** [comment]
Ok, I tested the first patch and landed it on the android branch : https://github.com/clutter-project/mx/commit/087572e0eb24d23c40b226c5726eda2d2a299f07 (needed to rewrite bits of the patch because lots of work has been done on kinetic scrollview).

**Comment by ManMower** [comment]
Sorry for the confusing forced push - the author requested that I change the e-mail address in the attribution.  Nothing else has changed.

**Comment by ManMower** [comment]
Since my forced push has divorced the commit from its comments, I'll add a reference to previous conversation here:

https://github.com/ManMower/mx/commit/e574b783b6e06f62df04ee5e1bf0f6d17cb19efd#-P0

Sorry!

**Comment by ManMower** [comment]
Updated to match upstream master

**Pull request closed without merging**
