### PR TITLE
Add a property to MxSlider to avoid live signalling

### PR DESCRIPTION
**Pull request by ghost**
When using an MxSlider to seek into a music media, you might want to only get signalled when the user release its mouse button with the slider at the desired position.

### CODE REVIEW

**Comment by Cwiiis** [comment]
Just a note, that to do this elsewhere in Mx, we use drag-begin and drag-end signals... Might be nicer to just fire off those signals and be consistent, rather than add a new property?

**Comment by ghost** [comment]
Agreed, I didn't know exactly how to name the signals.

**Comment by ghost** [comment]
Actually do you mean MxSlider should emit these signals?

**Comment by Cwiiis** [comment]
I did mean that, though looking at MxScrollBar, they're called scroll-start and scroll-stop. I guess in this case it ought to be slide-start and slide-stop?

**Comment by thos** [comment]
There's been another discussion about this issue here: http://bugzilla.clutter-project.org/show_bug.cgi?id=2677

**Comment by thos** [comment]
I think the value property is only updated once the drag has finished, so wouldn't that avoid any live updating?

**Comment by ghost** [comment]
Should we merge this patch from bugzilla instead ?

**Comment by Cwiiis** [comment]
The obsolete patch, yes (not the latest one that uses properties though): http://bugzilla.clutter-project.org/attachment.cgi?id=2708

**Comment by thos** [comment]
As I said in the original bug report, the patch needs some work to either
remove two padding pointers from the class struct, or not use class struct
members for the signals.

**Comment by ghost** [comment]
Resubmitting

**Pull request closed without merging**
