### PR TITLE
Fix: MxToggle honors disabled property.

### PR DESCRIPTION
**Pull request by fabiand**
Signed-off-by: Fabian Deutsch fabian.deutsch@gmx.de

### CODE REVIEW

**Comment by fabiand** [comment]
The widget is not clickable anymore, but the style is stillw rong. (So the disabled pseudo-selector isn't picked up)

**Comment by thos** [comment]
If you could fix up the commit message to include a bit more detail and ensure it conforms to the HACKING document, I'll merge it immediately.

**Comment by fabiand** [comment]
Okay.
Have you got any suggestions why the disabled selector might not work?

**Comment by fabiand** [comment]
I fixed the commit message. Hopefully with enough details and a propper tag.

**Comment by thos** [comment]
I made some minor tweaks to the message and committed to master. Thanks for the patch!

**Pull request closed without merging**
