### PR TITLE
mx-table: Clean up

### PR DESCRIPTION
**Pull request by magcius**
Be more consistent with the coding style internally, make the typical
cols/rows, width/height funcs more symmetrical

### CODE REVIEW

**Comment by magcius** [comment]
This isn't just a clean-up anymore. This actually fixes x-expand and y-expand for spanning (col-span/row-span) elements.

**Comment by magcius** [comment]
OK, I split out the column visibility fix from the x/y-expand fix.

**Comment by thos** [comment]
I'll cherry pick the fixes and wait until master is branched for 1.4 to commit the clean-up patches.

**Comment by thos** [comment]
Since the fixes may change behaviour, I've pushed these commits after the 1.4 branch.

**Pull request closed without merging**
