### PR TITLE
Pager

### PR DESCRIPTION
**Pull request by danni**
A pager widget as inspired by the Dawati wireframes

### CODE REVIEW

**Comment by thos** [comment]
Thanks for this patch; a couple of points:
- The widget is quite similar to MxNotebook. Would it make sense for it to be the same thing?
- Mx is currently targeting Clutter 1.10, which has a number of deprecations. The add, remove and foreach functions from ClutterContainer have been deprecated, as well as clutter_actor_lower_bottom.
- It would probably make sense to have the edge hover behaviour optional, as this is tricky to use if the mouse pointer is not restricted to the actor boundary.

**Comment by danni** [comment]
- I started playing with MxNotebook and it didn't seem to do what I wanted. It would make sense for them to be the same though. I wonder if there's a way to do the pager as a subclass of Notebook.
- Oh yeah, I meant to look at this.
- Yeah, that's planned.

Are you happy with the general approach? Building on top of MxStack feels a bit hacky, but it took a lot of the heavy lifting out of writing my own container.

**Comment by thos** [comment]
Building on top of MxStack may not be necessary with the new ClutterActor API, which handles a lot of the child management for you.

**Comment by danni** [comment]
Issues fixed.

So, I went back and looked at MxNotebook some more and I actually wonder whether MxNotebook is useful in a world with MxPager. We could easily add some more options to make MxPager more generic, i.e. being able to hide the pager buttons down the bottom, turn off the hot edges. What do you think?

Alternatively we could create an MxPageContainer widget as an abstract-base-class which contained all of the page turning logic and then subclasses would implement a change_page() vcall. However, I think that's probably overkill.

It looks like it will be relatively simple to port the widget off the top of MxStack by copying some code from MxNotebook, but I haven't done this yet.

**Comment by thos** [comment]
It probably makes sense for MxPager to have the options to turn off hot edges and pager buttons. This would also mean it can essentially replace MxNotebook.

**Comment by thos** [comment]
Please rebase the branch on master and merge it; the we can take a look at whether we can deprecate MxNotebook.

**Comment by danni** [comment]
Rebased and merged.

**Pull request closed without merging**
